{% set name = "parmoo" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parmoo-{{ version }}.tar.gz
  sha256: be65ebeea88039202decbaa6e547350184e8747572ea0a444e71074e71a0cb94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jax[cpu] >=0.4.13
    - numpy >=1.24.0
    - scipy >=1.10.0
    - libensemble >=1.4.2
    - pandas >=0.3.0
    - plotly >=5.20.0
    - dash >=2.9.3
    - python-kaleido >=0.2.1

test:
  imports:
    - parmoo
  commands:
    - py.test -m "not requires_chrome" --pyargs parmoo.tests.unit_tests
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/parmoo/parmoo
  summary: Python library for parallel multiobjective simulation optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wildsm
    - thchang
