{% set name = "parmoo" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parmoo-{{ version }}.tar.gz
  sha256: 08954310597596e5cf67a472184917ea5d683e678b66fe75b606f9345adf8ee6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jax[cpu] >=0.4.13
    - numpy >=1.24.0
    - scipy >=1.10.0
    - libensemble >=1.4.2
    - pandas >=0.3.0
    - plotly >=5.20.0
    - dash >=2.9.3
    - python-kaleido >=0.2.1

test:
  imports:
    - parmoo
  commands:
    - py.test --pyargs parmoo.tests.unit_tests
  requires:
    - chromedriver-binary
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/parmoo/parmoo
  summary: Python library for parallel multiobjective simulation optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wildsm
    - thchang
