{% set name = "parmoo" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parmoo-{{ version }}.tar.gz
  sha256: e449b6734cc30ec14719fd138a03e69eabf92afffe8daee8adaa2b992bbd34b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy >=1.10.0
    - pydoe
    - pandas
    - libensemble ==0.9.3
    - plotly
    - dash
    - python-kaleido

test:
  imports:
    - parmoo
  commands:
    - py.test --pyargs parmoo.tests.unit_tests
  requires:
    - pytest

about:
  home: https://github.com/parmoo/parmoo
  summary: Python library for parallel multiobjective simulation optimization
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wildsm
    - thchang
